celery:
    broker_url: redis://localhost/0
    result_backend: redis://localhost/0

collectors:
    - dummy-docker-collector
    - recon-ng
    - Certificate transparency
    - nmap

elasticsearch:
    endpoint:
        host: localhost
        port: 9200
