celery:
    broker_url: redis://localhost/0
    result_backend: redis://localhost/0

collectors:
    - b-collector

docker_registry:
    endpoint: localhost:5000

elasticsearch:
    endpoint:
        host: localhost
        port: 9200
