version: "3.3"

services:
  neo4j:
    image: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/root

########################
##  KIBANA
########################
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 5601:5601
    volumes:
     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

########################
##  ELASTICSEARCH
########################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data
    depends_on:
      - kibana

########################
##  FLOWER
########################
  flower:
    image: mher/flower:latest
    ports:
      - 5555:5555
    depends_on:
      - redis
    networks:
      - admin
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
########################
##  REDIS
########################
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    hostname: redis
    networks:
      - admin

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    networks:
      - admin


networks:
  elastic:
  admin:

volumes:
  elastic:
    driver: local
