version: "3.3"

services:
########################
##  KIBANA
########################
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - 127.0.0.1:5601:5601
    volumes:
     - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

########################
##  ELASTICSEARCH
########################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    networks:
      - elastic
    volumes:
      - elastic:/usr/share/elasticsearch/data
    depends_on: 
      - kibana

########################
##  FLOWER
########################
  flower:
    image: mher/flower:latest
    ports:
      - 127.0.0.1:5555:5555
    depends_on: 

########################
##  REDIS
########################
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379


networks:
  elastic:


volumes:
  elastic:
    driver: local
